# 기본 로그 레벨 설정
logging:
  level:
    root: warn
    com.ieung.receipt: debug
    org.hibernate.type.descriptor.sql: warn  # trace

spring:
  jwt:
    secret: DvqcGn8mnFjqSL4a
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
      show_sql: true
      use_sql_comments: true
    generate-ddl: true
    open-in-view: false

  # 데이터 베이스 연결 설정
  datasource:
    url: jdbc:mysql://localhost:3306/receipt_db?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: receipt
    password: Receipt!*
  flyway:
    enabled: false

  # 메일 전송 시 사용할 설정값
  mail:
    host: smtp.gmail.com
    port: 587
    username: keepMyReceiptByIeung@gmail.com
    password: Receipt!*
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  # 프로젝트 환경의 포트 설정
  port: 8185
  domain: http://127.0.0.1
  servlet:
    session:
      timeout: 1440m
  max-http-header-size: 3145728

aes256:
  key: WZsExuBV3GSQ55Uf

